'use client';
import Link from "next/link"; import {useEffect,useState} from "react"; import {collections} from "../lib/collections";
type H={arabic:string;english?:string;number?:string|number;grade?:string;source?:string;narrator?:string;collection?:string};
export default function Home(){const[dark,setDark]=useState(false);const[h,setH]=useState<H|null>(null);const[loading,setLoading]=useState(true);const[size,setSize]=useState(1);const[mode,setMode]=useState<"bilingual"|"arabic"|"english">("bilingual");const[saved,setSaved]=useState(false);
useEffect(()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});setDark(localStorage.getItem("nur-theme")==="dark");const k=localStorage.getItem("nur-last");if(k){try{setH(JSON.parse(k))}catch{}}},[]);
useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("nur-theme",dark?"dark":"light")},[dark]);
async function random(){setLoading(true);try{const r=await fetch("/api/random");if(!r.ok)throw new Error();const d=await r.json();const x=d.hadith||d;setH(x);localStorage.setItem("nur-last",JSON.stringify(x))}catch{}finally{setLoading(false)}}
useEffect(()=>{if(!h)random();else setLoading(false)},[]);
function toggleSave(){if(!h)return;const k=(h.collection||"")+"/"+h.number;const s=JSON.parse(localStorage.getItem("nur-saved")||"[]");const n=s.includes(k)?s.filter((x:string)=>x!==k):[...s,k];localStorage.setItem("nur-saved",JSON.stringify(n));setSaved(!s.includes(k))}
return <main className="home"><header className="topbar"><Link href="/" className="brand"><span>✦</span><div><b>Nur al-Hadith</b><small>نور الحديث</small></div></Link><nav><Link href="/collections">Collections</Link><Link href="/search">Search</Link><Link href="/library">My Library</Link><button onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?"☀":"☾"}</button></nav></header><section className="home-hero"><div><div className="eyebrow">نور الحديث · A DIGITAL HADITH LIBRARY</div><h1>Read the Sunnah<br/><em>with presence.</em></h1><p>A quiet, carefully structured place to read Arabic hadith, English translation, and source metadata across eight major collections.</p><div className="hero-actions"><Link href="/collections" className="primary">Explore collections</Link><button className="secondary" onClick={random}>Random hadith ↗</button></div></div><div className="hero-mark" aria-hidden="true">ﷺ</div></section><section className="daily"><div className="section-head"><div><span className="eyebrow">TODAY'S READING</span><h2>A narration for quiet reflection</h2></div><button onClick={random}>{loading?"Loading…":"Another narration ↻"}</button></div>{loading?<div className="skeleton"><span/><span/><span/></div>:h&&<article className="daily-card"><div className="daily-meta"><span>{h.source||"Hadith collection"}</span><button onClick={toggleSave}>{saved?"★ Saved":"☆ Save"}</button></div>{mode!=="english"&&<div className="daily-arabic" dir="rtl" style={{fontSize:1.9*size+"rem"}}>{h.arabic}</div>}{mode!=="arabic"&&h.english&&<p className="daily-english">{h.english}</p>}<div className="daily-foot"><span>{h.narrator||""}</span><strong>{h.grade||"Grade not supplied"}</strong></div><div className="reader-controls"><button className={mode==="arabic"?"active":""} onClick={()=>setMode("arabic")}>العربية</button><button className={mode==="bilingual"?"active":""} onClick={()=>setMode("bilingual")}>Bilingual</button><button className={mode==="english"?"active":""} onClick={()=>setMode("english")}>English</button><button onClick={()=>setSize(Math.max(.8,size-.1))}>A−</button><button onClick={()=>setSize(Math.min(1.5,size+.1))}>A+</button></div></article>}</section><section className="collection-section"><div className="section-head"><div><span className="eyebrow">THE LIBRARY</span><h2>Eight collections</h2></div><Link href="/collections">View all →</Link></div><div className="home-grid">{collections.map((c,i)=><Link href={"/collections/"+c.id} className="home-collection" key={c.id}><span>0{i+1}</span><div dir="rtl">{c.arabic}</div><h3>{c.name}</h3><p>{c.note}</p></Link>)}</div></section><footer className="home-footer"><span>نور الحديث</span><small>Source-aware reading · Private notes · Offline-ready PWA</small></footer></main>}
