'use client';
import Link from "next/link"; import {useEffect,useState} from "react"; import {useParams,useRouter} from "next/navigation"; import {collections} from "../../../lib/collections"; import type {Hadith} from "../../../lib/types";
export default function Reader(){const{book,id}=useParams<{book:string;id:string}>();const router=useRouter();const c=collections.find(x=>x.id===book);const[h,setH]=useState<Hadith|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[mode,setMode]=useState<"bilingual"|"arabic"|"english">("bilingual");const[size,setSize]=useState(1);const[saved,setSaved]=useState(false);const[note,setNote]=useState("");
const noteKey="nur-note-"+book+"-"+id; useEffect(()=>{setLoading(true);fetch("/api/hadith/"+book+"/"+id).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{const x=d.hadith||d;setH({...x,collection:book,number:x.idInBook||x.id||id,source:c?.name});setError("")}).catch(()=>setError("This hadith could not be loaded.")).finally(()=>setLoading(false));},[book,id,c?.name]);
useEffect(()=>{const s=JSON.parse(localStorage.getItem("nur-saved")||"[]");setSaved(s.includes(book+"-"+id));setNote(localStorage.getItem(noteKey)||"")},[book,id,noteKey]);useEffect(()=>{if(note)localStorage.setItem(noteKey,note)},[note,noteKey]);
function toggleSave(){const s=JSON.parse(localStorage.getItem("nur-saved")||"[]");const k=book+"-"+id;const next=s.includes(k)?s.filter((x:string)=>x!==k):[...s,k];localStorage.setItem("nur-saved",JSON.stringify(next));setSaved(!saved)}
async function share(){if(!h)return;const text=(h.arabic?h.arabic+"\n\n":"")+(h.english||"")+"\n\n"+(c?.name||"")+" "+h.number;if(navigator.share)await navigator.share({title:"Nur al-Hadith",text});else await navigator.clipboard.writeText(text)}
const next=Number(id)+1,prev=Math.max(1,Number(id)-1);
return <main className="shell reader-shell"><header className="readerbar"><Link href={c?"/collections/"+book:"/collections"} className="brand-link">← <span>{c?.name||"Collection"}</span></Link><div className="reader-actions"><button onClick={toggleSave}>{saved?"★ Saved":"☆ Save"}</button></div></header><div className="reader"><div className="eyebrow">{c?.name||book}</div>{loading&&<div className="skeleton"><span/><span/><span/></div>}{error&&<div className="error-box">{error}<button onClick={()=>router.refresh()}>Try again</button></div>}{h&&<><div className="reader-title"><span>Hadith {h.number}</span><span>{h.grade||"Grade not supplied"}</span></div><article className="reader-card">{mode!=="english"&&<div className="reader-arabic" dir="rtl" style={{fontSize:(1.9*size)+"rem"}}>{h.arabic}</div>}{mode!=="arabic"&&h.english&&<p className="reader-english">{h.english}</p>}{h.narrator&&<div className="reader-meta">Narrator: {h.narrator}</div>}<details><summary>Isnād / transmission details</summary><p>{h.isnad||"The available source record does not provide a separate isnād field."}</p></details></article><div className="reader-controls">{["arabic","bilingual","english"].map(m=><button key={m} className={mode===m?"active":""} onClick={()=>setMode(m as typeof mode)}>{m==="arabic"?"العربية":m[0].toUpperCase()+m.slice(1)}</button>)}<button onClick={()=>setSize(Math.max(.8,size-.1))}>A−</button><button onClick={()=>setSize(Math.min(1.5,size+.1))}>A+</button><button onClick={share}>Share</button></div><section className="note-panel"><div><div className="eyebrow">PRIVATE NOTE</div><h2>Study this narration</h2><p>Your note is stored locally on this device.</p></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Write a reflection or question…"/></section><nav className="prev-next"><Link href={"/read/"+book+"/"+prev}>← Previous</Link><span>Hadith {h.number}</span><Link href={"/read/"+book+"/"+next}>Next →</Link></nav></>}</div></main>}
