'use client';
import Link from "next/link"; import { useEffect,useState } from "react"; import { useParams } from "next/navigation"; import { collections } from "../../../lib/collections";
import {useLanguage} from "../../../components/LanguageProvider"; import LanguageSwitcher from "../../../components/LanguageSwitcher";
type Chapter={id:number;arabic:string;english:string;hadith_count:number;hadith_range:number[]}; type Info={total_hadiths:number;chapters:Chapter[]};
export default function CollectionPage(){const{t}=useLanguage();const{book}=useParams<{book:string}>();const c=collections.find(x=>x.id===book);const[info,setInfo]=useState<Info|null>(null);const[q,setQ]=useState("");
useEffect(()=>{let cancelled=false;fetch("/api/hadith/"+book).then(r=>r.ok?r.json():null).then((data:Info|null)=>{if(!cancelled)setInfo(data)}).catch(()=>{if(!cancelled)setInfo(null)});return()=>{cancelled=true}},[book]);
if(!c)return <main className="shell"><div className="page-content"><h1>{t("collectionNotFound")}</h1><Link href="/collections">{t("returnLibrary")}</Link></div></main>;
const chapters=(info?.chapters||[]).filter(x=>(x.english+" "+x.arabic).toLowerCase().includes(q.toLowerCase()));
return <main className="shell"><header className="pagebar"><Link href="/collections" className="brand-link">← <span>{t("collections")}</span></Link><div style={{display:"flex",alignItems:"center",gap:10}}><LanguageSwitcher/><Link href="/search" className="quiet-link">{t("search")}</Link></div></header><div className="page-content"><div className="eyebrow">{c.short}</div><h1 className="page-title">{c.name}</h1><div className="collection-stat">{info?.total_hadiths?.toLocaleString()||"—"} {t("hadiths")} · {info?.chapters.length||"—"} {t("chapters")}</div><input className="wide-search" value={q} onChange={e=>setQ(e.target.value)} placeholder={t("searchChapters")} aria-label={t("searchChapters")}/><div className="chapter-list">{chapters.map(ch=>{const firstHadith=ch.hadith_range[0];if(!firstHadith)return null;return <Link className="chapter-row" href={"/read/"+book+"/"+firstHadith} key={ch.id}><span>{String(ch.id).padStart(2,"0")}</span><div><b>{ch.english}</b><small dir="rtl">{ch.arabic}</small></div><em>{ch.hadith_count} {t("hadiths")} →</em></Link>})}</div></div></main>}
